pipeline:

  build:
    image: plugins/docker
    repo: kowalatech/mkdocs
    secrets: [ docker_username, docker_password ]
    tags: latest
    dockerfile: Dockerfile
    when:
      branch: [master]
      event: [push, tag]
